spring:
  application:
    name: sustainability-tracker
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sustainability_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: myPassword!
  jpa:
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
  jwt:
    secret: thisIsMySecretKeyAndItShouldBeLongEnough123456
    expiration: 86400000 # 24hr
  web:
    error:
      include-message: always
      include-stacktrace: never
      include-binding-errors: always
#    accessTokenExpiration: 7200 # 300 # 3m
#    refreshTokenExpiration: 604800 # 7d
kind: Application