spring:
  application:
    name: sustainability-tracker
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15m
    refreshTokenExpiration: 604800 # 7d
    isSecureCookie: true
  profiles:
    active: dev
app:
  report:
    storage-path: uploads/reports/
server:
  servlet:
#    context-path: /api/v1

kind: Application